//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemedioApi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_FcmToken
    {
        public int FcmTokenId { get; set; }
        public string FcmToken { get; set; }
    }
}
