//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemedioApi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Paciente()
        {
            this.tb_CaixaRemedio = new HashSet<tb_CaixaRemedio>();
            this.tb_Leitura = new HashSet<tb_Leitura>();
        }
    
        public int PacienteId { get; set; }
        public string PacienteNome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CaixaRemedio> tb_CaixaRemedio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Leitura> tb_Leitura { get; set; }
    }
}
